---
title: "Quick exploration of COVID-19 time series"
subtitle: "data provided by <br> Johns Hopkins Coronavirus Resource Center"
author: "Almond Stöcker"
date: "22 3 2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
# load libraries and data
library(dplyr)
library(reshape2)
library(lubridate)
library(ggplot2)
library(plotly)
library(magrittr)
library(stringr)
library(RColorBrewer)

data_rep <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/"

corona <- list(
  confirmed = read.csv(paste0(data_rep, "time_series_19-covid-Confirmed.csv"), check.names = FALSE),
  deaths = read.csv(paste0(data_rep, "time_series_19-covid-Deaths.csv"), check.names = FALSE),
  recovered = read.csv(paste0(data_rep, "time_series_19-covid-Recovered.csv"), check.names = FALSE)
)

# merge
corona <- bind_rows(corona, .id = "type")
# flatten in long format
corona <- corona %>% melt(id.vars = 1:5, variable.name = "date", value.name = "cases")
# convert date to proper date
corona <- corona %>% mutate(date = mdy(date))

## summarize countries
corona_country <- corona %>% 
  group_by(`Country/Region`, type, date) %>% summarise(cases = sum(cases)) %>%
  ungroup

## prepare ranking
corona_country_ranking <- corona_country %>% group_by(`Country/Region`) %>%
  filter(date == max(date), type == "confirmed") %>% ungroup %>% 
  arrange(cases) %>%
  mutate( `Country/Region` = ordered(`Country/Region`, levels = rev(`Country/Region`))) %>%
  .$`Country/Region`

# apply ranking
corona_country <- corona_country %>% 
  mutate(
    `Country/Region` = ordered(`Country/Region`, 
                               levels = levels(corona_country_ranking)),
    ranked_country = paste(
      str_pad(as.numeric(`Country/Region`), 3, pad = 0), 
      `Country/Region`))
selected_countries <- c("Germany", "France", "Spain", "US", "Italy", "United Kingdom")
subcorona <- corona_country %>% filter(`Country/Region` %in% selected_countries)
othercorona <- corona_country %>% filter(!(`Country/Region` %in% selected_countries))
```

## Worldwide overview on original scale

```{r}
# make repeating colors
cols <- brewer.pal(12, "Set3")[-2] %>% 
  rep(length(corona_country_ranking) %/% 11 + 1) %>% 
  head(length(corona_country_ranking))

# generate figures
make_subfig <- function(.type, .showlegend) {
  fig <- subcorona %>% 
  filter(type == .type) %>%  
  plot_ly(x = ~date, y = ~cases, legendgroup = ~as.character(`Country/Region`),
                             name = ~ranked_country,
                             color = ~ranked_country,
          colors = cols,
           type = "scatter", mode = "lines", showlegend = .showlegend)
  fig <- fig %>% add_trace(
    data = othercorona %>% filter(type == .type), showlegend = .showlegend,
                   visible = "legendonly")
}
figs <- list()
for(i in 1:3) {
  .type <- unique(subcorona$type)[i]
  figs[[i]] <- make_subfig( .type, c(TRUE,FALSE,FALSE)[i] )
  figs[[i]] %<>% layout(yaxis = list(title = .type))
}

fig_all <- do.call(subplot, c(figs, nrows = 3, shareX = TRUE, titleY = TRUE))

fig_all
```

## Worldwide overview on log scale

```{r}
figs <- lapply(figs, layout, yaxis = list(type = "log"))
fig_all <- do.call(subplot, c(figs, nrows = 3, shareX = TRUE, titleY = TRUE))
fig_all 
```

```{r}
# generate steps
steps <- list()
for(country in sort(unique(subcorona$`Country/Region`))) {
  step <- list(args = list('visible', country <= unique(subcorona$`Country/Region`)),
               method = 'restyle',
               label = country)
  steps[[country]] = step 
}
# apply steps
# fig_all %>%
#   layout(sliders = list(list(acitve = 1,
#                              currentvalue = list(prefix = "Not more confirmed than: "),
#                              steps = unname(steps))))

```

